apiVersion: apps/v1
kind: Deployment
metadata:
  name: arma-reforger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arma-server
  template:
    metadata:
      labels:
        app: arma-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: reforger
          image: ghcr.io/acemod/arma-reforger:latest
          ports:
            - containerPort: 2001
              protocol: UDP
              name: game-port
            - containerPort: 1999
              protocol: TCP
              name: rcon
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "7Gi"
              cpu: "3"
          env:
            - name: SERVER_BIND_ADDRESS
              value: "0.0.0.0"
            - name: SERVER_BIND_PORT
              value: "2001"
            - name: SERVER_PUBLIC_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: arma-public-address-secret
                  key: public-address
            - name: SERVER_PUBLIC_PORT
              value: "2001"
            - name: GAME_NAME
              value: "{{ .Values.game.name }}"
            - name: GAME_MAX_PLAYERS
              value: "{{ .Values.game.maxPlayers }}"
            - name: GAME_SCENARIO_ID
              value: "{{ .Values.game.scenarioId }}"
            - name: GAME_MODS_IDS_LIST
              value: "{{ .Values.game.modsList }}"
            - name: RCON_PORT
              value: "1999"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arma-rcon-secret
                  key: rcon-password
            - name: GAME_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arma-game-passwords
                  key: game-password
            - name: GAME_PASSWORD_ADMIN
              valueFrom:
                secretKeyRef:
                  name: arma-game-passwords
                  key: game-admin-password
            - name: GAME_VISIBLE
              value: "{{ .Values.game.visible }}"
            - name: GAME_ADMINS
              value: "{{ .Values.game.admins }}"
            - name: GAME_SUPPORTED_PLATFORMS
              value: "{{ .Values.game.supportedPlatforms }}"
            - name: GAME_PROPS_DISABLE_THIRD_PERSON
              value: "{{ .Values.game.disableThirdPerson }}"
            - name: GAME_PROPS_BATTLEYE
              value: "{{ .Values.game.battlEye }}"
            - name: GAME_PROPS_FAST_VALIDATION
              value: "{{ .Values.game.fastValidation }}"
            - name: GAME_PROPS_SERVER_MAX_VIEW_DISTANCE
              value: "{{ .Values.game.serverMaxViewDistance }}"
            - name: GAME_PROPS_SERVER_MIN_GRASS_DISTANCE
              value: "{{ .Values.game.serverMinGrassDistance }}"
            - name: GAME_PROPS_NETWORK_VIEW_DISTANCE
              value: "{{ .Values.game.networkViewDistance }}"
            - name: ARMA_PARAMS
              value: "-loadSessionSave"
          volumeMounts:
            - name: config-vol
              mountPath: /reforger/Configs
              subPath: Configs
            - name: profile-vol
              mountPath: /home/profile
              subPath: Profile
            - name: workshop-vol
              mountPath: /reforger/Workshop
              subPath: Workshop
      volumes:
        - name: config-vol
          persistentVolumeClaim:
            claimName: arma-game-pvc
        - name: profile-vol
          persistentVolumeClaim:
            claimName: arma-game-pvc
        - name: workshop-vol
          persistentVolumeClaim:
            claimName: arma-game-pvc