apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-aws-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: eso-aws-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: default
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-aws-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: eso-aws-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arma-rcon-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: arma-rcon-secret
  data:
    - secretKey: rcon-password
      remoteRef:
        key: /arma-reforger/rcon-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arma-public-address-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: arma-public-address-secret
  data:
    - secretKey: public-address
      remoteRef:
        key: /arma-reforger/public-address
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arma-game-passwords
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: arma-game-passwords
  data:
    - secretKey: game-password
      remoteRef:
        key: /arma-reforger/game-password
    - secretKey: game-admin-password
      remoteRef:
        key: /arma-reforger/game-admin-password
