apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arma-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arma-game-pv
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: arma-local-storage
  claimRef:
    name: arma-game-pvc
    namespace: default
  local:
    path: /opt/arma-server-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arma-reforger-compute

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arma-game-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: arma-local-storage
  resources:
    requests:
      storage: 40Gi